nome: str = input (" Qual o seu nome? ")
print ("olá", nome)
data: str = input (" Qual o dia do seu nascimento? ")
mes: str = input (" De que mês? ")
ano = input (" Qual o ano do seu nascimento? ")
n = int (2022)
n1= int (ano)
r = (n-n1)
print ("Você tem", r, 'anos de idade, correto?')
numero = input ("Digite um número")
r1 = int (numero)
r2 = (r + r1)
r4 = (r - r1)
r5 = (r * r1)
r6 = (r / r1)
print ("A soma entre sua idade e o valor que você digitou é", r2)
print ("A subtração entre a sua idade e o valor que você digitou é", r4)
print ("A multiplicação entre a sua idade e o valor que você digitou é", r5)
print ("A divisão entre a sua idade e o valor que você digitou é", r6)

